name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'dev' ]

permissions:
  contents: write
  actions: write

jobs:
  build_debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleGmsMobileUniversalDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-mobile-universal-debug
          path: |
            app/build/outputs/apk/gmsMobileUniversal/debug/*.apk
            app/build/outputs/apk/gms/mobile/universal/debug/*.apk
            app/build/outputs/apk/mobile/universal/debug/*.apk
